global:
  resolve_timeout: 5m

route:
  group_by: ['monitoring']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook'

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://monitoring-alerts:8080/alert'
        send_resolved: true
