global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets: ['alertmanager:9093']

rule_files:
  - 'alert.yml'

scrape_configs:
  - job_name: 'monitoring-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['monitoring-metrics:8081']
        labels:
          instance_group: monitoring-metrics
          instance_env: dev
          instance_name: monitoring-metrics
          instance_type: service
