global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'monitoring-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['monitoring-metrics:8081']

  - job_name: 'monitoring-dashboard'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['monitoring-dashboard:8082']
