spring:
  application:
    name: monitoring-metrics
    instance: instance-1

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  prometheus:
    metrics:
      export:
        enabled: true

prometheus:
  pushgateway:
    url: http://localhost:9091

metrics:
  push:
    interval: 6000
