server:
  port: 8081
spring:
  application:
    name: monitoring-metrics

  # Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: "always"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    com.monitor.metrics: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"